paths:
  caption_train_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/future_s1_train_caption_list' 
  caption_valid_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/future_s1_val_caption_list'
  vocab_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/vocabulary_breakfast_future.txt'
  data_p_path:  '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/data_breakfast_future.p'
  references_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/references_breakfast_future.p'
  corpus_p_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/corpus_breakfast_future.p'
  google_news_path: '/ais/fleet10/farzaneh/scn_captioning/data/GoogleNews-vectors-negative300.bin'
  gt_tag_feats_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/gt_tag_feats_breakfast_future.p' 
  
  hd5_train: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/future_breakfast_train_all.h5'
  hd5_valid: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/future_breakfast_val_all.h5'
  saving_path: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/breakfast_future_tagging_learned_params.npz'
  tag_feats_mat: '/ais/fleet10/farzaneh/scn_captioning/data/breakfast_future/tag_feats_pred_breakfast_future.mat'


  hd5_train: '../../data/breakfast_future/future_breakfast_train_all.h5'
  hd5_valid: '../../data/breakfast_future/future_breakfast_val_all.h5'
  tag_feats_pred_path: '../../data/breakfast_future/tag_feats_pred_breakfast_future.mat'
  corpus_p_path: "../../data/breakfast_future/corpus_breakfast_future.p"
  save_to_path: '../../data/breakfast_future/breakfast_future_result_scn_dropout.5_lr.002_0.npz'
  result_path: '../../data/breakfast_future/breakfast_future_result_scn_dropout.5_lr.002_'
  nbest: "../../data/breakfast_future/breakfast_future_nbest.p" 
  test_result: '../../data/breakfast_future/breakfast_future_scn_test_dropout.5_lr.002.txt'

params:  
  dropout: 0.5
  lr: 0.002
  max_epochs: 1
