paths:
  caption_train_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/s1_train_caption_list' 
  caption_valid_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/s1_val_caption_list'
  vocab_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_vocabulary.txt'
  data_p_path:  '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_data.p'
  references_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_references.p'
  corpus_p_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_corpus.p'
  google_news_path: '/ais/fleet10/farzaneh/scn_captioning/data/GoogleNews-vectors-negative300.bin'
  gt_tag_feats_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_gt_tag_feats.p' 
  
  hd5_train: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/breakfast_train_Cs_MTC.h5'
  hd5_valid: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/breakfast_val_Cs_MTC.h5'
  saving_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_tagging_learned_params.npz'
  tag_feats_mat: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_tag_feats_pred.mat'


  tag_feats_pred_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_tag_feats_pred.mat'
  corpus_p_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_corpus.p'
  save_to_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_result_scn_dropout.5_lr.002_0.npz'
  result_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_result_scn_dropout.5_lr.002_'
  nbest: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl__nbest.p'
  test_result: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/CsFl/CsFl_scn_test_dropout.5_lr.002.txt'

params:  
  keyword: "MTC"
  dropout: 0.5
  lr: 0.002
  max_epochs: 20
  n_x: 300
  n_hidden: 512
  n_f: 512
  batch_size: 64
  valid_batch_size: 64
   
