paths:
  caption_train_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/s1_train_caption_list' 
  caption_valid_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/s1_val_caption_list'
  vocab_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_vocabulary.txt'
  data_p_path:  '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_data.p'
  references_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_references.p'
  corpus_p_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_corpus.p'
  google_news_path: '/ais/fleet10/farzaneh/scn_captioning/data/GoogleNews-vectors-negative300.bin'
  gt_tag_feats_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_gt_tag_feats.p' 
  
  hd5_train: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/epicBreakfast_train_Fs_MTC.h5'
  hd5_valid: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/epicBreakfast_val_Fs_MTC.h5'
  saving_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_tagging_learned_params.npz'
  tag_feats_mat: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_tag_feats_pred.mat'


  tag_feats_pred_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_tag_feats_pred.mat'
  corpus_p_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_corpus.p'
  save_to_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_result_scn_dropout.5_lr.0002_0.npz'
  result_path: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_result_scn_dropout.5_lr.0002_'
  nbest: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl__nbest.p'
  test_result: '/ais/fleet10/farzaneh/scn_captioning/data/exp1_breakfast/FsFl/FsFl_scn_test_dropout.5_lr.0002.txt'

params:  
  keyword: "MTC"
  dropout: 0.5
  lr: 0.0002
  max_epochs: 20
  n_x: 300
  n_hidden: 512
  n_f: 512
  batch_size: 64
  valid_batch_size: 64
   
